[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.16.0"
  GO_VERSION = "1.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
