[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.16.0"
  
  # Add required environment variables for production
  VITE_API_ENDPOINT = "/.netlify/functions/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Remove functions section if not using Netlify Functions
