[build]
  base = "frontend/"
  publish = "frontend/dist/"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.16.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
